### ISSUE TITLE
Ghost rooms and servers

### ISSUE THREAD

**Issue by a13xmt** [a13xmt/matrixstats.org#39]
The rooms from the dead servers are not correctly removed, and still persist in some ratings like "new rooms" with very high priority. This rooms should be deleted. Server badges should be properly removed for deleted servers too.

**Comment by a13xmt** [comment]
Fixed in 0b5bc7021826fa07b8f8e654bcb7c23f671b986e and aff84c12b90f19abb376081eb59d0188220178e1

**Comment by MilkManzJourDaddy** [comment]
To clarify, as we discussed in the Matrix room, rooms **created** from a Homeserver that dies may live on.  But they retain the Room ID from the original Homeserver.  I.e. I created `!pUpkovgfAmvtNPmuLH:hackerspace.be` on the soon to be defunct hackerspace.be but the room will retain that ID, yet I set the main Alias as #TeslaTurbine:matrix.org and have Admin' MXIDs on other homeservers.  `↵↵¶`So, please clarify if n such a case, a room like this will not be abandonded by this project.  Thanks.
